### ISSUE TITLE
 Problem with KnpDisqusBundle

### ISSUE THREAD

**Issue by amanvarshney** [KnpLabs/KnpDisqusBundle#2]
i m trying to implement knpdisqusbundle but getting error 
You have requested a non-existent service "knp_disqus.forum.lorem". 
in my config.yml, i have written

```
knp_disqus: 
    api_key: my api key 
    forums: 
        lorem: 
            shortname: disqus shortname 
```

i have put the repository in `vendor->bundles->Knp->Bundle->DisqusBundle`. 

In Controller, i have written

```
  $comments = $this->get('knp_disqus.forum.lorem')->fetch(array( 
        'identifier' => '/december-2010/the-best-day-of-my-life/', 
        'limit' => 100, 
    )); 
```

Please help me out. i m not able to figureout this problem.
