### ISSUE TITLE
Lorem config ambiguity

### ISSUE THREAD

**Issue by benoitpointet** [KnpLabs/KnpDisqusBundle#3]
If one reads through this bundle documentation, one is tempted to believe that `lorem` in

```
 {{ knp_disqus_render('lorem', {'identifier': '/december-2010/the-best-day-of-my-life/', 'limit': 100}) }}
```

refers to the lorem forum as configured in the example `config.yml`

```
 knp_disqus:
    api_key: %knp_disqus.api_key%
    forums:
        lorem:
            shortname: %knp_disqus.lorem.shortname%
            cache: my_cache_for_lorem # cache template key, usage described below
```

whereas it in facts used as the Disqus shortname for a forum.
Moreover, the actual shortname parameter from the config doesn't seem much used.

We'd be glad to fix this ambiguity that if we could understand the intended behaviour: 
-  What is the first parameter of knp_disqus_render supposed to represent?
-  Should the KnpDisqusBundle allow for multiple forums on a same site?
