### ISSUE TITLE
Possiblity to use forum config key rather than short name

### ISSUE THREAD

**Issue by dantleech** [KnpLabs/KnpDisqusBundle#45]
Hi, we have a site which may have a different forum (Disqus) name in differnent environments, but it seems we need to reference the disqus name in the Twig template, e.g.:

```twig
    {{ knp_disqus_render('test-1234', {
```

Would be a nice feature to be able to reference the config key:

```yaml
    forums:
        myforum:
            shortname: test-1234
```

So `{{ knp_disqus_render('myforum', { blah }) }}`.

Or maybe there is a better way? and thanks for the bundle :)
